### ISSUE TITLE
Empty or missing SD card causes reboot abort

### ISSUE THREAD

**Issue by billkendrick** [FujiNetWIFI/fujinet-config#15]
Attempting to access the SD slot when no SD card is present, or when the SD card is empty, causes CONFIG to crash. Pressing a key (e.g., [Backspace] aka "DELETE / Up Dir") causes a reboot of the Atari.

When the SD card is empty, I noticed "ERROR SETTING DIRECTORY POS" appear when entering the SD slot.

**Comment by jhusak** [comment]
As version of 12 may 2021 the config does not crash, but displays "EMPTY" text. This is a "file" that can be assigned to slot and then in slot there is garbage shown.
![IMG_1348](https://user-images.githubusercontent.com/1560095/118040061-60b3bb00-b371-11eb-9600-ce840efc55dc.JPG)

**Comment by mozzwald** [comment]
The commit which closed this issue fixes the problem with being able to mount the empty/garbage file. Unfortunately, it also disables the ability to create a new disk image on a blank SD card. Reopening

**Comment by mozzwald** [comment]
and we're back :D reopening cuz latest commit reintroduces ability to mount --Empty-- to a slot

**Comment by mozzwald** [comment]
Fixed in d33247ebbfb5166564d8cf5538ccf61fb5b938fc
