### ISSUE TITLE
Joystick based page up/down disk browsing

### ISSUE THREAD

**Issue by r3mowilliams** [FujiNetWIFI/fujinet-config#18]
Enhancement request: Allow option for the user to page up/down with joystick left/right in disk image browsing

**Comment by tschak909** [comment]
Yup! Very doable!

**Comment by tschak909** [comment]
Fixed in commit: https://github.com/FujiNetWIFI/fujinet-config/commit/37b52be76ad7ea4919dde8473c9bd81832a373a9 Closing.
