### ISSUE TITLE
Make CONFIG work without WiFi connection for SD card use only

### ISSUE THREAD

**Issue by mozzwald** [FujiNetWIFI/fujinet-config#24]
Currently CONFIG requires connection to WiFi before it will get you to the HOST/DISK slot menu. There should be a way to skip WiFi connection (a SSID named -SKIP- might be a good idea). Then while using CONFIG, if WiFi connection is not available disable use of TNFS servers and only allow SD access for mounts.

**Comment by tschak909** [comment]
On it.
