### ISSUE TITLE
Cannot bypass WIFI Setup and/or Airplane Mode

### ISSUE THREAD

**Issue by schlutech** [FujiNetWIFI/fujinet-config#25]
The fujinet can be used with SD locally - but there doesn't appear to be a way to bypass wifi setup. 

Wifi/networking issues can make the fujinet misbehave and/or slow down even when working just with the SD card. 

Atari can not be used someplace without WIFI. 

The Atari could be used someplace where you are required to disable WIFI/BT etc (airplane mode.)

Also a Fujinet that is broken might still work with the SD card.

**Comment by tschak909** [comment]
I have checked in code to skip wifi configuration, as of today.
-Thom

**Comment by mozzwald** [comment]
Already fixed with ba786d90a76a62628fe3f8a462694ef3c59af33b

**Comment by schlutech** [comment]
I missed it!
Well my laziness shines out like a beacon only surpassed with my annoying personality.

(Thanks guys.)
